version: "3.8"

services:
  redwardenlite:
    build:
      context: ../..
      dockerfile: deploy/container/Dockerfile
    container_name: redwardenlite
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../../example-config.yaml:/config/config.yaml:ro
      - ../../artifacts:/opt/RedWardenLite/artifacts
    command: ["python", "RedWardenLite.py", "--config", "/config/config.yaml"]
